### ISSUE TITLE
[BUG] Unable to run zippy -h

### ISSUE THREAD

**Issue by vivekprajapati2048** [thinkst/zippy#13]
I want to implement this repository. I cloned it on my windows machine and followed `Readme.md` file for the installation using `pip3`. However, after successful installation, I ran into following error while trying to run `zippy -h`:  

```
(venv) C:\Users\HP\PycharmProjects\zippy>zippy -h 
Traceback (most recent call last):
  File "C:\Users\HP\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main                              
    return _run_code(code, main_globals, None,                                                                                           
  File "C:\Users\HP\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code                                         
    exec(code, run_globals)                                                                                                              
  File "C:\Users\HP\PycharmProjects\zippy\venv\Scripts\zippy.exe\__main__.py", line 4, in <module>      
  File "C:\Users\HP\PycharmProjects\zippy\venv\lib\site-packages\zippy\__init__.py", line 1, in <module>
    from .zippy import *
  File "C:\Users\HP\PycharmProjects\zippy\venv\lib\site-packages\zippy\zippy.py", line 44, in <module>
    PRELUDE_STR = clean_text(files('zippy').joinpath(PRELUDE_FILE).read_text())
  File "C:\Users\HP\AppData\Local\Programs\Python\Python310\lib\pathlib.py", line 1135, in read_text
    return f.read()
  File "C:\Users\HP\AppData\Local\Programs\Python\Python310\lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x81 in position 54323: character maps to <undefined>
```

Can you please let me know if there is any step which I am missing?

**Comment by ranok** [comment]
Thank you @vivekprajapati2048 for reporting this. It appears that I need to explicitly set a character encoding when reading files. I will make a couple fixes and ping you shortly to retest.

**Comment by asun146** [comment]
Is this resolved? I'm seeing the same issue.

**Comment by ranok** [comment]
Are you on Windows as well?

**Comment by ranok** [comment]
@asun146 Can you try building from source?

This is now working on my Windows 11 box, I need to push a new release

**Comment by ranok** [comment]
@asun146 @vivekprajapati2048 I have pushed a fix to PyPi, v0.1.3 should work on Windows OSes now.
